Wdp190701 12
Varenthein/WDP-1907-01 pull request #12
Opened 2019-07-31 09:18 UTC by DorotaAdamska

**Opis problemu:**
Strona sypie się w trybach responsive. Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 

Ten task dotyczy górnego paska (z walutą, językiem, etc.) oraz bannera na którym jest logo i inne elementy. 

Na tabletach wygląda ok, ale na mobilkach trzeba poprawić: 

top bar

- dropdowny po lewej mają pozostać bez zmian
- login i register mają być bez tekstów (tylko ikony)
- w razie potrzeby można zmniejszyć marginy/paddingi wszystkich elementów, ale tylko w trybach w których jest to potrzebne
- ta ikona menu po prawej na topbarze ma zostać, zarówno na mobilkach jak i desktopie, Klient później zdecyduje co chce tam mieć i czy zmieni się ikona

banner

- po lewej ma być logo
- po prawej koszyk (wyrównany do góry logo, czyli trochę wyżej niż jest)
- po koszykiem ma być telefon (ikona i numer)
- numer telefonu można zmniejszyć do 14px

**Opis rozwiązania:**
- dodałam klasy z boostrapa ukrywające i odkrywające poszczególne elementy 
- poprawiłam style niektórych elementów w headerze na ekranach poniżej 576px

2019-08-02 07:43 UTC, Johny1010 approved these changes

2019-08-04 11:22 UTC, Varenthein requested changes
Look at this:

![image](https://user-images.githubusercontent.com/13353257/62422938-ca8e3380-b6ba-11e9-9710-839cc031d79d.png)

I think this "Help" on the bottom doesn't look too good. And there is still plenty of space in the first row. Please do something about it.

2019-08-05 08:48 UTC, DorotaAdamska commented
@Varenthein You have absolutely right, it doesn't look nice. I'll fix it.

2019-08-06 06:55 UTC, Varenthein approved these changes

2019-08-06 06:55 UTC, merged