Wdp190701-19
Varenthein/WDP-1907-01 pull request #24
Opened 2019-08-20 11:25 UTC by markal84

Trzeba napisać JS do gwiazdek. Nie używamy żadnego pluginu, piszemy własny skrypt do tego. 

**Rozwiązanie:**

- Stworzyłem skrypt który reaguje na zdarzenia _click_, _mouseenter_, _mouseleave_

- _click_ zamraża gwiazdki nadając im ocenę
- _mouseenter_ służy do zaznaczania gwiazdek
- _mouseleave_ służy do odznaczania gwiazdek jeśli gwiazdki nie zostały kliknięte i nie uruchomiło się zdarzenie _click_

2019-08-20 18:19 UTC, Varenthein requested changes
It looks good. I'd only use additional functions `addStarsClass`, `removeStarsClass`. Try to keep DRY ;)

2019-08-20 19:00 UTC, DorotaAdamska commented
Jak dla mnie działa prawidłowo :)

2019-08-20 19:37 UTC, markal84 commented
> Jak dla mnie działa prawidłowo :) Trzeba będzie jednak rozwiązać konflikty...

Fixed :)

2019-08-21 05:55 UTC, DorotaAdamska approved these changes

2019-08-21 13:45 UTC, markal84 commented
> It looks good. I'd only use additional functions `addStarsClass`, `removeStarsClass`. Try to keep DRY ;)

I added  `addStarsClass`, `removeStarsClass` functions to avoid repeating. I left code in `click` event because it gives different class on click so it's unique code.

2019-08-22 17:57 UTC, merged